# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import analyzer_pb2 as analyzer__pb2


class AnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAnalyzer = channel.unary_unary(
                '/Analyzer/StartAnalyzer',
                request_serializer=analyzer__pb2.StartAnalyzerReq.SerializeToString,
                response_deserializer=analyzer__pb2.StartAnalyzerRes.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/Analyzer/GetStatus',
                request_serializer=analyzer__pb2.GetStatusReq.SerializeToString,
                response_deserializer=analyzer__pb2.GetStatusRes.FromString,
                )


class AnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartAnalyzer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAnalyzer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAnalyzer,
                    request_deserializer=analyzer__pb2.StartAnalyzerReq.FromString,
                    response_serializer=analyzer__pb2.StartAnalyzerRes.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=analyzer__pb2.GetStatusReq.FromString,
                    response_serializer=analyzer__pb2.GetStatusRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Analyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Analyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartAnalyzer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Analyzer/StartAnalyzer',
            analyzer__pb2.StartAnalyzerReq.SerializeToString,
            analyzer__pb2.StartAnalyzerRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Analyzer/GetStatus',
            analyzer__pb2.GetStatusReq.SerializeToString,
            analyzer__pb2.GetStatusRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
