# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\"\x12\n\x10StartAnalyzerReq\"\x12\n\x10StartAnalyzerRes\"\x0e\n\x0cGetStatusReq\"\x1e\n\x0cGetStatusRes\x12\x0e\n\x06status\x18\x01 \x01(\t2p\n\x08\x41nalyzer\x12\x37\n\rStartAnalyzer\x12\x11.StartAnalyzerReq\x1a\x11.StartAnalyzerRes\"\x00\x12+\n\tGetStatus\x12\r.GetStatusReq\x1a\r.GetStatusRes\"\x00\x62\x06proto3')



_STARTANALYZERREQ = DESCRIPTOR.message_types_by_name['StartAnalyzerReq']
_STARTANALYZERRES = DESCRIPTOR.message_types_by_name['StartAnalyzerRes']
_GETSTATUSREQ = DESCRIPTOR.message_types_by_name['GetStatusReq']
_GETSTATUSRES = DESCRIPTOR.message_types_by_name['GetStatusRes']
StartAnalyzerReq = _reflection.GeneratedProtocolMessageType('StartAnalyzerReq', (_message.Message,), {
  'DESCRIPTOR' : _STARTANALYZERREQ,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:StartAnalyzerReq)
  })
_sym_db.RegisterMessage(StartAnalyzerReq)

StartAnalyzerRes = _reflection.GeneratedProtocolMessageType('StartAnalyzerRes', (_message.Message,), {
  'DESCRIPTOR' : _STARTANALYZERRES,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:StartAnalyzerRes)
  })
_sym_db.RegisterMessage(StartAnalyzerRes)

GetStatusReq = _reflection.GeneratedProtocolMessageType('GetStatusReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATUSREQ,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:GetStatusReq)
  })
_sym_db.RegisterMessage(GetStatusReq)

GetStatusRes = _reflection.GeneratedProtocolMessageType('GetStatusRes', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATUSRES,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:GetStatusRes)
  })
_sym_db.RegisterMessage(GetStatusRes)

_ANALYZER = DESCRIPTOR.services_by_name['Analyzer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTANALYZERREQ._serialized_start=18
  _STARTANALYZERREQ._serialized_end=36
  _STARTANALYZERRES._serialized_start=38
  _STARTANALYZERRES._serialized_end=56
  _GETSTATUSREQ._serialized_start=58
  _GETSTATUSREQ._serialized_end=72
  _GETSTATUSRES._serialized_start=74
  _GETSTATUSRES._serialized_end=104
  _ANALYZER._serialized_start=106
  _ANALYZER._serialized_end=218
# @@protoc_insertion_point(module_scope)
