# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\x16\x64\x61k_keyword_worker.svc\"\x12\n\x10StartAnalyzerReq\"\"\n\x10StartAnalyzerRes\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0e\n\x0cGetStatusReq\".\n\x0cGetStatusRes\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xcc\x01\n\x08\x41nalyzer\x12\x65\n\rStartAnalyzer\x12(.dak_keyword_worker.svc.StartAnalyzerReq\x1a(.dak_keyword_worker.svc.StartAnalyzerRes\"\x00\x12Y\n\tGetStatus\x12$.dak_keyword_worker.svc.GetStatusReq\x1a$.dak_keyword_worker.svc.GetStatusRes\"\x00\x42\x39Z7github.com/aglide100/dak-keyword-twitter-scraper/pb/svcb\x06proto3')



_STARTANALYZERREQ = DESCRIPTOR.message_types_by_name['StartAnalyzerReq']
_STARTANALYZERRES = DESCRIPTOR.message_types_by_name['StartAnalyzerRes']
_GETSTATUSREQ = DESCRIPTOR.message_types_by_name['GetStatusReq']
_GETSTATUSRES = DESCRIPTOR.message_types_by_name['GetStatusRes']
StartAnalyzerReq = _reflection.GeneratedProtocolMessageType('StartAnalyzerReq', (_message.Message,), {
  'DESCRIPTOR' : _STARTANALYZERREQ,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:dak_keyword_worker.svc.StartAnalyzerReq)
  })
_sym_db.RegisterMessage(StartAnalyzerReq)

StartAnalyzerRes = _reflection.GeneratedProtocolMessageType('StartAnalyzerRes', (_message.Message,), {
  'DESCRIPTOR' : _STARTANALYZERRES,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:dak_keyword_worker.svc.StartAnalyzerRes)
  })
_sym_db.RegisterMessage(StartAnalyzerRes)

GetStatusReq = _reflection.GeneratedProtocolMessageType('GetStatusReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATUSREQ,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:dak_keyword_worker.svc.GetStatusReq)
  })
_sym_db.RegisterMessage(GetStatusReq)

GetStatusRes = _reflection.GeneratedProtocolMessageType('GetStatusRes', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATUSRES,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:dak_keyword_worker.svc.GetStatusRes)
  })
_sym_db.RegisterMessage(GetStatusRes)

_ANALYZER = DESCRIPTOR.services_by_name['Analyzer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/aglide100/dak-keyword-twitter-scraper/pb/svc'
  _STARTANALYZERREQ._serialized_start=42
  _STARTANALYZERREQ._serialized_end=60
  _STARTANALYZERRES._serialized_start=62
  _STARTANALYZERRES._serialized_end=96
  _GETSTATUSREQ._serialized_start=98
  _GETSTATUSREQ._serialized_end=112
  _GETSTATUSRES._serialized_start=114
  _GETSTATUSRES._serialized_end=160
  _ANALYZER._serialized_start=163
  _ANALYZER._serialized_end=367
# @@protoc_insertion_point(module_scope)
