# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanager.proto\x12\x0epb.svc.manager\"1\n\x0f\x43reateNewJobReq\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\"C\n\x0f\x43reateNewJobRes\x12\x0f\n\x07keyword\x18\x01 \x03(\t\x12\x10\n\x08workerId\x18\x02 \x03(\t\x12\r\n\x05jobId\x18\x03 \x01(\t\",\n\x0fGetJobStatusReq\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\"!\n\x0fGetJobStatusRes\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x18\n\nStopJobReq\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\nStopJobRes\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1c\n\x0e\x44oneScraperReq\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x0e\x44oneScraperRes\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1d\n\x0f\x44oneAnalyzerReq\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x0f\x44oneAnalyzerRes\x12\x0e\n\x06status\x18\x01 \x01(\t2\x91\x03\n\x07Manager\x12P\n\x0c\x43reateNewJob\x12\x1f.pb.svc.manager.CreateNewJobReq\x1a\x1f.pb.svc.manager.CreateNewJobRes\x12P\n\x0cGetJobStatus\x12\x1f.pb.svc.manager.GetJobStatusReq\x1a\x1f.pb.svc.manager.GetJobStatusRes\x12M\n\x0b\x44oneScraper\x12\x1e.pb.svc.manager.DoneScraperReq\x1a\x1e.pb.svc.manager.DoneScraperRes\x12P\n\x0c\x44oneAnalyzer\x12\x1f.pb.svc.manager.DoneAnalyzerReq\x1a\x1f.pb.svc.manager.DoneAnalyzerRes\x12\x41\n\x07StopJob\x12\x1a.pb.svc.manager.StopJobReq\x1a\x1a.pb.svc.manager.StopJobResB1Z/github.com/aglide100/dak-keyword/pb/svc/managerb\x06proto3')



_CREATENEWJOBREQ = DESCRIPTOR.message_types_by_name['CreateNewJobReq']
_CREATENEWJOBRES = DESCRIPTOR.message_types_by_name['CreateNewJobRes']
_GETJOBSTATUSREQ = DESCRIPTOR.message_types_by_name['GetJobStatusReq']
_GETJOBSTATUSRES = DESCRIPTOR.message_types_by_name['GetJobStatusRes']
_STOPJOBREQ = DESCRIPTOR.message_types_by_name['StopJobReq']
_STOPJOBRES = DESCRIPTOR.message_types_by_name['StopJobRes']
_DONESCRAPERREQ = DESCRIPTOR.message_types_by_name['DoneScraperReq']
_DONESCRAPERRES = DESCRIPTOR.message_types_by_name['DoneScraperRes']
_DONEANALYZERREQ = DESCRIPTOR.message_types_by_name['DoneAnalyzerReq']
_DONEANALYZERRES = DESCRIPTOR.message_types_by_name['DoneAnalyzerRes']
CreateNewJobReq = _reflection.GeneratedProtocolMessageType('CreateNewJobReq', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWJOBREQ,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.CreateNewJobReq)
  })
_sym_db.RegisterMessage(CreateNewJobReq)

CreateNewJobRes = _reflection.GeneratedProtocolMessageType('CreateNewJobRes', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWJOBRES,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.CreateNewJobRes)
  })
_sym_db.RegisterMessage(CreateNewJobRes)

GetJobStatusReq = _reflection.GeneratedProtocolMessageType('GetJobStatusReq', (_message.Message,), {
  'DESCRIPTOR' : _GETJOBSTATUSREQ,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.GetJobStatusReq)
  })
_sym_db.RegisterMessage(GetJobStatusReq)

GetJobStatusRes = _reflection.GeneratedProtocolMessageType('GetJobStatusRes', (_message.Message,), {
  'DESCRIPTOR' : _GETJOBSTATUSRES,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.GetJobStatusRes)
  })
_sym_db.RegisterMessage(GetJobStatusRes)

StopJobReq = _reflection.GeneratedProtocolMessageType('StopJobReq', (_message.Message,), {
  'DESCRIPTOR' : _STOPJOBREQ,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.StopJobReq)
  })
_sym_db.RegisterMessage(StopJobReq)

StopJobRes = _reflection.GeneratedProtocolMessageType('StopJobRes', (_message.Message,), {
  'DESCRIPTOR' : _STOPJOBRES,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.StopJobRes)
  })
_sym_db.RegisterMessage(StopJobRes)

DoneScraperReq = _reflection.GeneratedProtocolMessageType('DoneScraperReq', (_message.Message,), {
  'DESCRIPTOR' : _DONESCRAPERREQ,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.DoneScraperReq)
  })
_sym_db.RegisterMessage(DoneScraperReq)

DoneScraperRes = _reflection.GeneratedProtocolMessageType('DoneScraperRes', (_message.Message,), {
  'DESCRIPTOR' : _DONESCRAPERRES,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.DoneScraperRes)
  })
_sym_db.RegisterMessage(DoneScraperRes)

DoneAnalyzerReq = _reflection.GeneratedProtocolMessageType('DoneAnalyzerReq', (_message.Message,), {
  'DESCRIPTOR' : _DONEANALYZERREQ,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.DoneAnalyzerReq)
  })
_sym_db.RegisterMessage(DoneAnalyzerReq)

DoneAnalyzerRes = _reflection.GeneratedProtocolMessageType('DoneAnalyzerRes', (_message.Message,), {
  'DESCRIPTOR' : _DONEANALYZERRES,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.manager.DoneAnalyzerRes)
  })
_sym_db.RegisterMessage(DoneAnalyzerRes)

_MANAGER = DESCRIPTOR.services_by_name['Manager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/aglide100/dak-keyword/pb/svc/manager'
  _CREATENEWJOBREQ._serialized_start=33
  _CREATENEWJOBREQ._serialized_end=82
  _CREATENEWJOBRES._serialized_start=84
  _CREATENEWJOBRES._serialized_end=151
  _GETJOBSTATUSREQ._serialized_start=153
  _GETJOBSTATUSREQ._serialized_end=197
  _GETJOBSTATUSRES._serialized_start=199
  _GETJOBSTATUSRES._serialized_end=232
  _STOPJOBREQ._serialized_start=234
  _STOPJOBREQ._serialized_end=258
  _STOPJOBRES._serialized_start=260
  _STOPJOBRES._serialized_end=288
  _DONESCRAPERREQ._serialized_start=290
  _DONESCRAPERREQ._serialized_end=318
  _DONESCRAPERRES._serialized_start=320
  _DONESCRAPERRES._serialized_end=352
  _DONEANALYZERREQ._serialized_start=354
  _DONEANALYZERREQ._serialized_end=383
  _DONEANALYZERRES._serialized_start=385
  _DONEANALYZERRES._serialized_end=418
  _MANAGER._serialized_start=421
  _MANAGER._serialized_end=822
# @@protoc_insertion_point(module_scope)
